language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

script:
  - bash -ex .travis-opam.sh

env:
  global:
    - HIEROGLYPHS_ROOT="$HOME/build/marcoonroad/hieroglyphs/.hieroglyphs"
    - PACKAGE=hieroglyphs
    - UPDATE_GCC_BINUTILS=1
    - BISECT_ENABLE=YES
    - BISECT_SILENT=YES
    - POST_INSTALL_HOOK="make report"
  matrix:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07

os:
  - linux

before_script:
  - mkdir -p $HIEROGLYPHS_ROOT
  - mkdir -p $HIEROGLYPHS_ROOT/blacklist
  - cd $HIEROGLYPHS_ROOT/blacklist && git init --bare --shared && cd $OLDPWD
  - chmod -R a+rwx $HIEROGLYPHS_ROOT

cache:
  directories:
    - $HIEROGLYPHS_ROOT
