language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

script:
  - bash -ex .travis-opam.sh

env:
  global:
    - HIEROGLYPHS_ROOT=/tmp/hieroglyphs
    - PACKAGE=hieroglyphs
    - UPDATE_GCC_BINUTILS=1
    - BISECT_ENABLE=YES
    - BISECT_SILENT=YES
    - POST_INSTALL_HOOK="make report"
  matrix:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07

os:
  - linux

cache:
  directories:
    - $HIEROGLYPHS_ROOT
